//File Automatically generated by SystemC Netlister Time
#ifndef BD_D216_SCI_H
#define BD_D216_SCI_H
#include "systemc.h"
#include "xtlm.h"
#include "utils/xtlm_aximm_transview.h"
#include "utils/xtlm_aximm_transaction_logger.h"
#include "utils/xtlm_axis_transaction_logger.h"
#include "bd_d216_interconnect_M00_AXI_MEM00_0_sc.h"
#include "bd_d216_rs_M00_AXI_0_sc.h"
#if (defined MTI_SYSTEMC || defined XM_SYSTEMC) && defined XSC_ENABLE_TLM_WAVEFORM 
#include "scv.h"
#endif
#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM 
#include "cve.h"
#endif


class bd_d216_sci : public xsc::utils::xsc_sim_conn_base {

public:
	//Exported sockets declaration
		xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* S01_AXI_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* S04_AXI_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* S04_AXI_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_initiator_socket* M00_AXI_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_initiator_socket* M00_AXI_tlm_aximm_write_socket;;
	
	//Constructor for the module
	bd_d216_sci(const sc_module_name& module_name);
	SC_HAS_PROCESS(bd_d216_sci);
	//Destructor for the module
	~bd_d216_sci();
	
	void initConnModule();

protected:
void before_end_of_elaboration();

private:
	bd_d216_sci(const bd_d216_sci&);
	const bd_d216_sci& operator=(const bd_d216_sci&);
};
#endif
