//File Automatically generated by SystemC Netlister Time
#include "pfm_top_sci.h"
pfm_top_sci::pfm_top_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_top_sci","C0_DDR4_S_AXI_CTRL_0_tlm_MODE",0,"pfm_top_sim_ddr_0_0","C0_DDR4_S_AXI_CTRL_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_top_sci","C0_DDR4_S_AXI_CTRL_0_tlm_MODE",0,"pfm_top_sim_ddr_0_0","C0_DDR4_S_AXI_CTRL_TLM_MODE");
	
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_clock_converter_0_0","M_AXI_TLM_MODE","pfm_top_sim_ddr_0_0","C0_DDR4_S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_clock_converter_0_0","M_AXI_TLM_MODE","pfm_top_sim_ddr_0_0","C0_DDR4_S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_0_0","M_AXI_TLM_MODE","pfm_top_sim_address_0_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_0_0","M_AXI_TLM_MODE","pfm_top_sim_address_0_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_embedded_schedular_0","m_axi_data_m2m_TLM_MODE","pfm_top_smartconnect_0_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_embedded_schedular_0","m_axi_data_m2m_TLM_MODE","pfm_top_smartconnect_0_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_qdma_0_0","M_AXIMM_TLM_MODE","pfm_top_smartconnect_0_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_qdma_0_0","M_AXIMM_TLM_MODE","pfm_top_smartconnect_0_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M00_AXI_tlm_MODE","pfm_top_axi_vip_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M00_AXI_tlm_MODE","pfm_top_axi_vip_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M01_AXI_tlm_MODE","pfm_top_axi_vip_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M01_AXI_tlm_MODE","pfm_top_axi_vip_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M02_AXI_tlm_MODE","pfm_top_axi_vip_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M02_AXI_tlm_MODE","pfm_top_axi_vip_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M03_AXI_tlm_MODE","pfm_top_axi_vip_3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M03_AXI_tlm_MODE","pfm_top_axi_vip_3_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M04_AXI_tlm_MODE","pfm_top_embedded_schedular_0","s_axi_data_p2p_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_smartconnect_0_0","M04_AXI_tlm_MODE","pfm_top_embedded_schedular_0","s_axi_data_p2p_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_sci","PLP_M_AXI_DATA_U2S_00_tlm_MODE","pfm_top_axi_clock_converter_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_sci","PLP_M_AXI_DATA_U2S_00_tlm_MODE","pfm_top_axi_clock_converter_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_1_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_01_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_1_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_01_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_2_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_02_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_2_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_02_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_3_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_03_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_axi_vip_3_0","M_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_03_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_address_0_0","M_AXIMM_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_00_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_address_0_0","M_AXIMM_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_DATA_H2C_00_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_qdma_0_0","M_AXICTRL_TLM_MODE","pfm_top_xbar_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_sim_qdma_0_0","M_AXICTRL_TLM_MODE","pfm_top_xbar_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M00_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_CTRL_USER_00_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M00_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_CTRL_USER_00_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M04_AXI_TLM_MODE","pfm_top_embedded_schedular_0","s_axi_ctrl_user_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M04_AXI_TLM_MODE","pfm_top_embedded_schedular_0","s_axi_ctrl_user_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_embedded_schedular_0","maxi_lite_mb_TLM_MODE","pfm_top_xbar_0","S01_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_embedded_schedular_0","maxi_lite_mb_TLM_MODE","pfm_top_xbar_0","S01_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M01_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_CTRL_USER_01_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_top_xbar_0","M01_AXI_TLM_MODE","pfm_dynamic_sci","PLP_S_AXI_CTRL_USER_01_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("pfm_top_sci","C0_DDR4_0_TLM_MODE",-1);
	
	xsc::utils::xsc_sim_manager::addInstance("pfm_top_sci", this);
	#if defined MTI_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()) {
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	scv_startup(); /* Initialize SCV: */
	scv_tr_wlf_init(); /* Tie databases to WLF: */
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
	#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()){
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	cve_tr_sdi_init();
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
}
pfm_top_sci::~pfm_top_sci()
{
}
void pfm_top_sci::initConnModule() {

	pfm_top_sim_ddr_0_0_sc*  inst0=dynamic_cast<pfm_top_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_ddr_0_0"));
	registerTlmSocket("C0_DDR4_S_AXI_CTRL_0_tlm_aximm_read_socket",inst0->C0_DDR_SAXI_CTRL_rd_socket);
	pfm_top_sim_ddr_0_0_sc*  inst1=dynamic_cast<pfm_top_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_ddr_0_0"));
	registerTlmSocket("C0_DDR4_S_AXI_CTRL_0_tlm_aximm_write_socket",inst1->C0_DDR_SAXI_CTRL_wr_socket);
}

void pfm_top_sci::before_end_of_elaboration() {
	
	pfm_top_axi_clock_converter_0_0_sc*  inst_0=dynamic_cast<pfm_top_axi_clock_converter_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_clock_converter_0_0"));
	pfm_top_sim_ddr_0_0_sc*  inst_1=dynamic_cast<pfm_top_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_ddr_0_0"));
	xtlm_aximm_transaction_logger* log_inst_0 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_0");
	log_inst_0->setProxyRef(inst_0, inst_1, "pfm_top_axi_clock_converter_0_0_M_AXI_TLM", "pfm_top_sim_ddr_0_0_C0_DDR4_S_AXI_TLM", log_inst_0->m_transactionLogger);
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_clock_converter_0_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_ddr_0_0_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->M_INITIATOR_rd_socket->bind(*(log_inst_0->tar_rd_skt));
		log_inst_0->init_rd_skt->bind(*(inst_1->C0_DDR_SAXI_rd_socket));
	}
	
	pfm_top_axi_clock_converter_0_0_sc*  inst_4=dynamic_cast<pfm_top_axi_clock_converter_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_clock_converter_0_0"));
	pfm_top_sim_ddr_0_0_sc*  inst_5=dynamic_cast<pfm_top_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_ddr_0_0"));
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_clock_converter_0_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_ddr_0_0_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->M_INITIATOR_wr_socket->bind(*(log_inst_0->tar_wr_skt));
		log_inst_0->init_wr_skt->bind(*(inst_5->C0_DDR_SAXI_wr_socket));
	}
	
	pfm_top_axi_vip_0_0_sc*  inst_8=dynamic_cast<pfm_top_axi_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_0_0"));
	pfm_top_sim_address_0_0_sc*  inst_9=dynamic_cast<pfm_top_sim_address_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_address_0_0"));
	xtlm_aximm_transaction_logger* log_inst_1 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_1");
	log_inst_1->setProxyRef(inst_8, inst_9, "pfm_top_axi_vip_0_0_M_AXI_TLM", "pfm_top_sim_address_0_0_S_AXIMM_TLM", log_inst_1->m_transactionLogger);
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_0_0_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_address_0_0_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->M_INITIATOR_rd_socket->bind(*(log_inst_1->tar_rd_skt));
		log_inst_1->init_rd_skt->bind(*(inst_9->S_TARGET_rd_socket));
	}
	
	pfm_top_axi_vip_0_0_sc*  inst_12=dynamic_cast<pfm_top_axi_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_0_0"));
	pfm_top_sim_address_0_0_sc*  inst_13=dynamic_cast<pfm_top_sim_address_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_address_0_0"));
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_0_0_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_address_0_0_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->M_INITIATOR_wr_socket->bind(*(log_inst_1->tar_wr_skt));
		log_inst_1->init_wr_skt->bind(*(inst_13->S_TARGET_wr_socket));
	}
	
	pfm_top_embedded_schedular_0_sc*  inst_16=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	pfm_top_smartconnect_0_0_sc*  inst_17=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	xtlm_aximm_transaction_logger* log_inst_2 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_2");
	log_inst_2->setProxyRef(inst_16, inst_17, "pfm_top_embedded_schedular_0_m_axi_data_m2m_TLM", "pfm_top_smartconnect_0_0_S01_AXI_tlm", log_inst_2->m_transactionLogger);
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->m_axi_data_m2m_rd_socket->bind(*(log_inst_2->tar_rd_skt));
		log_inst_2->init_rd_skt->bind(*(inst_17->S01_AXI_tlm_aximm_read_socket));
	}
	
	pfm_top_embedded_schedular_0_sc*  inst_20=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	pfm_top_smartconnect_0_0_sc*  inst_21=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->m_axi_data_m2m_wr_socket->bind(*(log_inst_2->tar_wr_skt));
		log_inst_2->init_wr_skt->bind(*(inst_21->S01_AXI_tlm_aximm_write_socket));
	}
	
	pfm_top_sim_qdma_0_0_sc*  inst_24=dynamic_cast<pfm_top_sim_qdma_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_qdma_0_0"));
	pfm_top_smartconnect_0_0_sc*  inst_25=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	xtlm_aximm_transaction_logger* log_inst_3 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_3");
	log_inst_3->setProxyRef(inst_24, inst_25, "pfm_top_sim_qdma_0_0_M_AXIMM_TLM", "pfm_top_smartconnect_0_0_S00_AXI_tlm", log_inst_3->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_qdma_0_0_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->initiator_mm_rd_socket->bind(*(log_inst_3->tar_rd_skt));
		log_inst_3->init_rd_skt->bind(*(inst_25->S00_AXI_tlm_aximm_read_socket));
	}
	
	pfm_top_sim_qdma_0_0_sc*  inst_28=dynamic_cast<pfm_top_sim_qdma_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_qdma_0_0"));
	pfm_top_smartconnect_0_0_sc*  inst_29=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_qdma_0_0_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->initiator_mm_wr_socket->bind(*(log_inst_3->tar_wr_skt));
		log_inst_3->init_wr_skt->bind(*(inst_29->S00_AXI_tlm_aximm_write_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_32=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_0_0_sc*  inst_33=dynamic_cast<pfm_top_axi_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_0_0"));
	xtlm_aximm_transaction_logger* log_inst_4 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_4");
	log_inst_4->setProxyRef(inst_32, inst_33, "pfm_top_smartconnect_0_0_M00_AXI_tlm", "pfm_top_axi_vip_0_0_S_AXI_TLM", log_inst_4->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_0_0_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_4->tar_rd_skt));
		log_inst_4->init_rd_skt->bind(*(inst_33->S_TARGET_rd_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_36=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_0_0_sc*  inst_37=dynamic_cast<pfm_top_axi_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_0_0"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_0_0_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_4->tar_wr_skt));
		log_inst_4->init_wr_skt->bind(*(inst_37->S_TARGET_wr_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_40=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_1_0_sc*  inst_41=dynamic_cast<pfm_top_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_1_0"));
	xtlm_aximm_transaction_logger* log_inst_5 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_5");
	log_inst_5->setProxyRef(inst_40, inst_41, "pfm_top_smartconnect_0_0_M01_AXI_tlm", "pfm_top_axi_vip_1_0_S_AXI_TLM", log_inst_5->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_1_0_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->M01_AXI_tlm_aximm_read_socket->bind(*(log_inst_5->tar_rd_skt));
		log_inst_5->init_rd_skt->bind(*(inst_41->S_TARGET_rd_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_44=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_1_0_sc*  inst_45=dynamic_cast<pfm_top_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_1_0"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_1_0_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->M01_AXI_tlm_aximm_write_socket->bind(*(log_inst_5->tar_wr_skt));
		log_inst_5->init_wr_skt->bind(*(inst_45->S_TARGET_wr_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_48=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_2_0_sc*  inst_49=dynamic_cast<pfm_top_axi_vip_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_2_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_48, inst_49, "pfm_top_smartconnect_0_0_M02_AXI_tlm", "pfm_top_axi_vip_2_0_S_AXI_TLM", log_inst_6->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_2_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->M02_AXI_tlm_aximm_read_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_49->S_TARGET_rd_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_52=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_2_0_sc*  inst_53=dynamic_cast<pfm_top_axi_vip_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_2_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_2_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->M02_AXI_tlm_aximm_write_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_53->S_TARGET_wr_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_56=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_3_0_sc*  inst_57=dynamic_cast<pfm_top_axi_vip_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_3_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_56, inst_57, "pfm_top_smartconnect_0_0_M03_AXI_tlm", "pfm_top_axi_vip_3_0_S_AXI_TLM", log_inst_7->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_3_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->M03_AXI_tlm_aximm_read_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_57->S_TARGET_rd_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_60=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_axi_vip_3_0_sc*  inst_61=dynamic_cast<pfm_top_axi_vip_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_3_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_3_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->M03_AXI_tlm_aximm_write_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_61->S_TARGET_wr_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_64=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_embedded_schedular_0_sc*  inst_65=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	xtlm_aximm_transaction_logger* log_inst_8 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_8");
	log_inst_8->setProxyRef(inst_64, inst_65, "pfm_top_smartconnect_0_0_M04_AXI_tlm", "pfm_top_embedded_schedular_0_s_axi_data_p2p_TLM", log_inst_8->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->M04_AXI_tlm_aximm_read_socket->bind(*(log_inst_8->tar_rd_skt));
		log_inst_8->init_rd_skt->bind(*(inst_65->s_axi_data_p2p_rd_socket));
	}
	
	pfm_top_smartconnect_0_0_sc*  inst_68=dynamic_cast<pfm_top_smartconnect_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_smartconnect_0_0"));
	pfm_top_embedded_schedular_0_sc*  inst_69=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_smartconnect_0_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->M04_AXI_tlm_aximm_write_socket->bind(*(log_inst_8->tar_wr_skt));
		log_inst_8->init_wr_skt->bind(*(inst_69->s_axi_data_p2p_wr_socket));
	}
	
	xsc_sim_conn_base*  inst_72=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	pfm_top_axi_clock_converter_0_0_sc*  inst_73=dynamic_cast<pfm_top_axi_clock_converter_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_clock_converter_0_0"));
	
	if(inst_72==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	if(inst_73==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_clock_converter_0_0_sc, Skipping this connection"<<std::endl;
	}
	
	if (inst_72!=NULL && inst_73!=NULL && inst_72->getTlmSocketByName("PLP_M_AXI_DATA_U2S_00_tlm_aximm_read_socket")!=NULL) {
		static_cast<xtlm::xtlm_aximm_initiator_socket*>(inst_72->getTlmSocketByName("PLP_M_AXI_DATA_U2S_00_tlm_aximm_read_socket"))->bind(*(inst_73->S_TARGET_rd_socket));
	}
	
	xsc_sim_conn_base*  inst_76=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	pfm_top_axi_clock_converter_0_0_sc*  inst_77=dynamic_cast<pfm_top_axi_clock_converter_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_clock_converter_0_0"));
	
	if(inst_76==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	if(inst_77==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_clock_converter_0_0_sc, Skipping this connection"<<std::endl;
	}
	
	if (inst_76!=NULL && inst_77!=NULL && inst_76->getTlmSocketByName("PLP_M_AXI_DATA_U2S_00_tlm_aximm_write_socket")!=NULL) {
		static_cast<xtlm::xtlm_aximm_initiator_socket*>(inst_76->getTlmSocketByName("PLP_M_AXI_DATA_U2S_00_tlm_aximm_write_socket"))->bind(*(inst_77->S_TARGET_wr_socket));
	}
	
	pfm_top_axi_vip_1_0_sc*  inst_80=dynamic_cast<pfm_top_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_1_0"));
	xsc_sim_conn_base*  inst_81=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_80==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_1_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_81==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_80!=NULL && inst_81!=NULL && inst_81->getTlmSocketByName("PLP_S_AXI_DATA_H2C_01_tlm_aximm_read_socket")!=NULL) {
		inst_80->M_INITIATOR_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_81->getTlmSocketByName("PLP_S_AXI_DATA_H2C_01_tlm_aximm_read_socket")));
	}
	
	pfm_top_axi_vip_1_0_sc*  inst_84=dynamic_cast<pfm_top_axi_vip_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_1_0"));
	xsc_sim_conn_base*  inst_85=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_84==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_1_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_85==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_84!=NULL && inst_85!=NULL && inst_85->getTlmSocketByName("PLP_S_AXI_DATA_H2C_01_tlm_aximm_write_socket")!=NULL) {
		inst_84->M_INITIATOR_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_85->getTlmSocketByName("PLP_S_AXI_DATA_H2C_01_tlm_aximm_write_socket")));
	}
	
	pfm_top_axi_vip_2_0_sc*  inst_88=dynamic_cast<pfm_top_axi_vip_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_2_0"));
	xsc_sim_conn_base*  inst_89=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_88==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_2_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_89==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_88!=NULL && inst_89!=NULL && inst_89->getTlmSocketByName("PLP_S_AXI_DATA_H2C_02_tlm_aximm_read_socket")!=NULL) {
		inst_88->M_INITIATOR_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_89->getTlmSocketByName("PLP_S_AXI_DATA_H2C_02_tlm_aximm_read_socket")));
	}
	
	pfm_top_axi_vip_2_0_sc*  inst_92=dynamic_cast<pfm_top_axi_vip_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_2_0"));
	xsc_sim_conn_base*  inst_93=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_92==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_2_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_93==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_92!=NULL && inst_93!=NULL && inst_93->getTlmSocketByName("PLP_S_AXI_DATA_H2C_02_tlm_aximm_write_socket")!=NULL) {
		inst_92->M_INITIATOR_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_93->getTlmSocketByName("PLP_S_AXI_DATA_H2C_02_tlm_aximm_write_socket")));
	}
	
	pfm_top_axi_vip_3_0_sc*  inst_96=dynamic_cast<pfm_top_axi_vip_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_3_0"));
	xsc_sim_conn_base*  inst_97=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_96==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_3_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_97==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_96!=NULL && inst_97!=NULL && inst_97->getTlmSocketByName("PLP_S_AXI_DATA_H2C_03_tlm_aximm_read_socket")!=NULL) {
		inst_96->M_INITIATOR_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_97->getTlmSocketByName("PLP_S_AXI_DATA_H2C_03_tlm_aximm_read_socket")));
	}
	
	pfm_top_axi_vip_3_0_sc*  inst_100=dynamic_cast<pfm_top_axi_vip_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_axi_vip_3_0"));
	xsc_sim_conn_base*  inst_101=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_100==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_axi_vip_3_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_101==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_100!=NULL && inst_101!=NULL && inst_101->getTlmSocketByName("PLP_S_AXI_DATA_H2C_03_tlm_aximm_write_socket")!=NULL) {
		inst_100->M_INITIATOR_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_101->getTlmSocketByName("PLP_S_AXI_DATA_H2C_03_tlm_aximm_write_socket")));
	}
	
	pfm_top_sim_address_0_0_sc*  inst_104=dynamic_cast<pfm_top_sim_address_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_address_0_0"));
	xsc_sim_conn_base*  inst_105=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_104==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_sim_address_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_105==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_104!=NULL && inst_105!=NULL && inst_105->getTlmSocketByName("PLP_S_AXI_DATA_H2C_00_tlm_aximm_read_socket")!=NULL) {
		inst_104->M_INITIATOR_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_105->getTlmSocketByName("PLP_S_AXI_DATA_H2C_00_tlm_aximm_read_socket")));
	}
	
	pfm_top_sim_address_0_0_sc*  inst_108=dynamic_cast<pfm_top_sim_address_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_address_0_0"));
	xsc_sim_conn_base*  inst_109=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_108==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_sim_address_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_109==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_108!=NULL && inst_109!=NULL && inst_109->getTlmSocketByName("PLP_S_AXI_DATA_H2C_00_tlm_aximm_write_socket")!=NULL) {
		inst_108->M_INITIATOR_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_109->getTlmSocketByName("PLP_S_AXI_DATA_H2C_00_tlm_aximm_write_socket")));
	}
	
	pfm_top_sim_qdma_0_0_sc*  inst_112=dynamic_cast<pfm_top_sim_qdma_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_qdma_0_0"));
	pfm_top_xbar_0_sc*  inst_113=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xtlm_aximm_transaction_logger* log_inst_14 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_14");
	log_inst_14->setProxyRef(inst_112, inst_113, "pfm_top_sim_qdma_0_0_M_AXICTRL_TLM", "pfm_top_xbar_0_S00_AXI_TLM", log_inst_14->m_transactionLogger);
	
	if(inst_112==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_qdma_0_0_sc"<<std::endl;
	}
	if(inst_113==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	
	if (inst_112!=NULL && inst_113!=NULL) {
		inst_112->initiator_ctrl_rd_socket->bind(*(log_inst_14->tar_rd_skt));
		log_inst_14->init_rd_skt->bind(*(inst_113->target_0_rd_socket));
	}
	
	pfm_top_sim_qdma_0_0_sc*  inst_116=dynamic_cast<pfm_top_sim_qdma_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_sim_qdma_0_0"));
	pfm_top_xbar_0_sc*  inst_117=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	
	if(inst_116==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_sim_qdma_0_0_sc"<<std::endl;
	}
	if(inst_117==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	
	if (inst_116!=NULL && inst_117!=NULL) {
		inst_116->initiator_ctrl_wr_socket->bind(*(log_inst_14->tar_wr_skt));
		log_inst_14->init_wr_skt->bind(*(inst_117->target_0_wr_socket));
	}
	
	pfm_top_xbar_0_sc*  inst_120=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xsc_sim_conn_base*  inst_121=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_120==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_121==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_120!=NULL && inst_121!=NULL && inst_121->getTlmSocketByName("PLP_S_AXI_CTRL_USER_00_tlm_aximm_read_socket")!=NULL) {
		inst_120->initiator_0_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_121->getTlmSocketByName("PLP_S_AXI_CTRL_USER_00_tlm_aximm_read_socket")));
	}
	
	pfm_top_xbar_0_sc*  inst_124=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xsc_sim_conn_base*  inst_125=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_124==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_125==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_124!=NULL && inst_125!=NULL && inst_125->getTlmSocketByName("PLP_S_AXI_CTRL_USER_00_tlm_aximm_write_socket")!=NULL) {
		inst_124->initiator_0_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_125->getTlmSocketByName("PLP_S_AXI_CTRL_USER_00_tlm_aximm_write_socket")));
	}
	
	pfm_top_xbar_0_sc*  inst_128=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	pfm_top_embedded_schedular_0_sc*  inst_129=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	xtlm_aximm_transaction_logger* log_inst_16 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_16");
	log_inst_16->setProxyRef(inst_128, inst_129, "pfm_top_xbar_0_M04_AXI_TLM", "pfm_top_embedded_schedular_0_s_axi_ctrl_user_TLM", log_inst_16->m_transactionLogger);
	
	if(inst_128==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	if(inst_129==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	
	if (inst_128!=NULL && inst_129!=NULL) {
		inst_128->initiator_4_rd_socket->bind(*(log_inst_16->tar_rd_skt));
		log_inst_16->init_rd_skt->bind(*(inst_129->s_axi_ctrl_user_rd_socket));
	}
	
	pfm_top_xbar_0_sc*  inst_132=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	pfm_top_embedded_schedular_0_sc*  inst_133=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	
	if(inst_132==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	if(inst_133==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	
	if (inst_132!=NULL && inst_133!=NULL) {
		inst_132->initiator_4_wr_socket->bind(*(log_inst_16->tar_wr_skt));
		log_inst_16->init_wr_skt->bind(*(inst_133->s_axi_ctrl_user_wr_socket));
	}
	
	pfm_top_embedded_schedular_0_sc*  inst_136=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	pfm_top_xbar_0_sc*  inst_137=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xtlm_aximm_transaction_logger* log_inst_17 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_17");
	log_inst_17->setProxyRef(inst_136, inst_137, "pfm_top_embedded_schedular_0_maxi_lite_mb_TLM", "pfm_top_xbar_0_S01_AXI_TLM", log_inst_17->m_transactionLogger);
	
	if(inst_136==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	if(inst_137==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	
	if (inst_136!=NULL && inst_137!=NULL) {
		inst_136->maxi_lite_mb_rd_socket->bind(*(log_inst_17->tar_rd_skt));
		log_inst_17->init_rd_skt->bind(*(inst_137->target_1_rd_socket));
	}
	
	pfm_top_embedded_schedular_0_sc*  inst_140=dynamic_cast<pfm_top_embedded_schedular_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_embedded_schedular_0"));
	pfm_top_xbar_0_sc*  inst_141=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	
	if(inst_140==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_embedded_schedular_0_sc"<<std::endl;
	}
	if(inst_141==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc"<<std::endl;
	}
	
	if (inst_140!=NULL && inst_141!=NULL) {
		inst_140->maxi_lite_mb_wr_socket->bind(*(log_inst_17->tar_wr_skt));
		log_inst_17->init_wr_skt->bind(*(inst_141->target_1_wr_socket));
	}
	
	pfm_top_xbar_0_sc*  inst_144=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xsc_sim_conn_base*  inst_145=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_144==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_145==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_144!=NULL && inst_145!=NULL && inst_145->getTlmSocketByName("PLP_S_AXI_CTRL_USER_01_tlm_aximm_read_socket")!=NULL) {
		inst_144->initiator_1_rd_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_145->getTlmSocketByName("PLP_S_AXI_CTRL_USER_01_tlm_aximm_read_socket")));
	}
	
	pfm_top_xbar_0_sc*  inst_148=dynamic_cast<pfm_top_xbar_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_top_xbar_0"));
	xsc_sim_conn_base*  inst_149=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sci"));
	
	if(inst_148==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_top_xbar_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_149==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_148!=NULL && inst_149!=NULL && inst_149->getTlmSocketByName("PLP_S_AXI_CTRL_USER_01_tlm_aximm_write_socket")!=NULL) {
		inst_148->initiator_1_wr_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_149->getTlmSocketByName("PLP_S_AXI_CTRL_USER_01_tlm_aximm_write_socket")));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(pfm_top_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(pfm_top_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(pfm_top_sci);
#endif

