-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity kvadd_kvadd_Pipeline_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_m01_axi_AWVALID : OUT STD_LOGIC;
    m_axi_m01_axi_AWREADY : IN STD_LOGIC;
    m_axi_m01_axi_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_m01_axi_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_m01_axi_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_m01_axi_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_m01_axi_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_WVALID : OUT STD_LOGIC;
    m_axi_m01_axi_WREADY : IN STD_LOGIC;
    m_axi_m01_axi_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_m01_axi_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_m01_axi_WLAST : OUT STD_LOGIC;
    m_axi_m01_axi_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_ARVALID : OUT STD_LOGIC;
    m_axi_m01_axi_ARREADY : IN STD_LOGIC;
    m_axi_m01_axi_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_m01_axi_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_m01_axi_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_m01_axi_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_m01_axi_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_m01_axi_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_RVALID : IN STD_LOGIC;
    m_axi_m01_axi_RREADY : OUT STD_LOGIC;
    m_axi_m01_axi_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_m01_axi_RLAST : IN STD_LOGIC;
    m_axi_m01_axi_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_m01_axi_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_BVALID : IN STD_LOGIC;
    m_axi_m01_axi_BREADY : OUT STD_LOGIC;
    m_axi_m01_axi_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_m01_axi_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_m01_axi_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln74 : IN STD_LOGIC_VECTOR (57 downto 0);
    m01_axi_output_buffer_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    m01_axi_output_buffer_ce0 : OUT STD_LOGIC;
    m01_axi_output_buffer_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of kvadd_kvadd_Pipeline_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv480_lc_1 : STD_LOGIC_VECTOR (479 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal empty_38_reg_225 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_38_reg_225_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal exitcond2112_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal m01_axi_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond2112_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_38_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal m01_axi_output_buffer_load_reg_235 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal loop_index6_cast9_fu_128_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal shiftreg37_fu_64 : STD_LOGIC_VECTOR (479 downto 0);
    signal empty_36_fu_184_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal loop_index6_fu_68 : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_35_fu_122_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_sig_allocacmp_loop_index6_load : STD_LOGIC_VECTOR (12 downto 0);
    signal empty_37_fu_133_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_167_p4 : STD_LOGIC_VECTOR (447 downto 0);
    signal tmp_6_fu_177_p3 : STD_LOGIC_VECTOR (479 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component kvadd_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component kvadd_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    loop_index6_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (exitcond2112_fu_116_p2 = ap_const_lv1_0))) then 
                    loop_index6_fu_68 <= empty_35_fu_122_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    loop_index6_fu_68 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;

    shiftreg37_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    shiftreg37_fu_64 <= ap_const_lv480_lc_1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    shiftreg37_fu_64 <= empty_36_fu_184_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                empty_38_reg_225_pp0_iter1_reg <= empty_38_reg_225;
                exitcond2112_reg_216 <= exitcond2112_fu_116_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond2112_fu_116_p2 = ap_const_lv1_0))) then
                empty_38_reg_225 <= empty_38_fu_137_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond2112_reg_216 = ap_const_lv1_0))) then
                m01_axi_output_buffer_load_reg_235 <= m01_axi_output_buffer_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(m_axi_m01_axi_WREADY, empty_38_reg_225_pp0_iter1_reg)
    begin
                ap_block_state3_io <= ((empty_38_reg_225_pp0_iter1_reg = ap_const_lv1_1) and (m_axi_m01_axi_WREADY = ap_const_logic_0));
    end process;

        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, exitcond2112_fu_116_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond2112_fu_116_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, exitcond2112_reg_216)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond2112_reg_216 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_loop_index6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, loop_index6_fu_68)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_loop_index6_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_loop_index6_load <= loop_index6_fu_68;
        end if; 
    end process;

    empty_35_fu_122_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_loop_index6_load) + unsigned(ap_const_lv13_1));
    empty_36_fu_184_p3 <= 
        ap_const_lv480_lc_1 when (empty_38_reg_225_pp0_iter1_reg(0) = '1') else 
        tmp_6_fu_177_p3;
    empty_37_fu_133_p1 <= ap_sig_allocacmp_loop_index6_load(4 - 1 downto 0);
    empty_38_fu_137_p2 <= "1" when (empty_37_fu_133_p1 = ap_const_lv4_F) else "0";
    exitcond2112_fu_116_p2 <= "1" when (ap_sig_allocacmp_loop_index6_load = ap_const_lv13_1000) else "0";
    loop_index6_cast9_fu_128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_loop_index6_load),64));

    m01_axi_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_m01_axi_WREADY, empty_38_reg_225_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (empty_38_reg_225_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m01_axi_blk_n_W <= m_axi_m01_axi_WREADY;
        else 
            m01_axi_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    m01_axi_output_buffer_address0 <= loop_index6_cast9_fu_128_p1(13 - 1 downto 0);

    m01_axi_output_buffer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m01_axi_output_buffer_ce0 <= ap_const_logic_1;
        else 
            m01_axi_output_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_m01_axi_ARADDR <= ap_const_lv64_0;
    m_axi_m01_axi_ARBURST <= ap_const_lv2_0;
    m_axi_m01_axi_ARCACHE <= ap_const_lv4_0;
    m_axi_m01_axi_ARID <= ap_const_lv1_0;
    m_axi_m01_axi_ARLEN <= ap_const_lv32_0;
    m_axi_m01_axi_ARLOCK <= ap_const_lv2_0;
    m_axi_m01_axi_ARPROT <= ap_const_lv3_0;
    m_axi_m01_axi_ARQOS <= ap_const_lv4_0;
    m_axi_m01_axi_ARREGION <= ap_const_lv4_0;
    m_axi_m01_axi_ARSIZE <= ap_const_lv3_0;
    m_axi_m01_axi_ARUSER <= ap_const_lv1_0;
    m_axi_m01_axi_ARVALID <= ap_const_logic_0;
    m_axi_m01_axi_AWADDR <= ap_const_lv64_0;
    m_axi_m01_axi_AWBURST <= ap_const_lv2_0;
    m_axi_m01_axi_AWCACHE <= ap_const_lv4_0;
    m_axi_m01_axi_AWID <= ap_const_lv1_0;
    m_axi_m01_axi_AWLEN <= ap_const_lv32_0;
    m_axi_m01_axi_AWLOCK <= ap_const_lv2_0;
    m_axi_m01_axi_AWPROT <= ap_const_lv3_0;
    m_axi_m01_axi_AWQOS <= ap_const_lv4_0;
    m_axi_m01_axi_AWREGION <= ap_const_lv4_0;
    m_axi_m01_axi_AWSIZE <= ap_const_lv3_0;
    m_axi_m01_axi_AWUSER <= ap_const_lv1_0;
    m_axi_m01_axi_AWVALID <= ap_const_logic_0;
    m_axi_m01_axi_BREADY <= ap_const_logic_0;
    m_axi_m01_axi_RREADY <= ap_const_logic_0;
    m_axi_m01_axi_WDATA <= (m01_axi_output_buffer_load_reg_235 & shiftreg37_fu_64);
    m_axi_m01_axi_WID <= ap_const_lv1_0;
    m_axi_m01_axi_WLAST <= ap_const_logic_0;
    m_axi_m01_axi_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_m01_axi_WUSER <= ap_const_lv1_0;

    m_axi_m01_axi_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, empty_38_reg_225_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (empty_38_reg_225_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            m_axi_m01_axi_WVALID <= ap_const_logic_1;
        else 
            m_axi_m01_axi_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_fu_167_p4 <= shiftreg37_fu_64(479 downto 32);
    tmp_6_fu_177_p3 <= (m01_axi_output_buffer_load_reg_235 & tmp_5_fu_167_p4);
end behav;
