//File Automatically generated by SystemC Netlister Time
#ifndef PFM_TOP_SCI_H
#define PFM_TOP_SCI_H
#include "systemc.h"
#include "xtlm.h"
#include "utils/xtlm_aximm_transview.h"
#include "utils/xtlm_aximm_transaction_logger.h"
#include "utils/xtlm_axis_transaction_logger.h"
#include "pfm_top_axi_clock_converter_0_0_sc.h"
#include "pfm_top_sim_ddr_0_0_sc.h"
#include "pfm_top_axi_vip_0_0_sc.h"
#include "pfm_top_sim_address_0_0_sc.h"
#include "pfm_top_embedded_schedular_0_sc.h"
#include "pfm_top_smartconnect_0_0_sc.h"
#include "pfm_top_sim_qdma_0_0_sc.h"
#include "pfm_top_axi_vip_1_0_sc.h"
#include "pfm_top_axi_vip_2_0_sc.h"
#include "pfm_top_axi_vip_3_0_sc.h"
#include "pfm_top_xbar_0_sc.h"
#if (defined MTI_SYSTEMC || defined XM_SYSTEMC) && defined XSC_ENABLE_TLM_WAVEFORM 
#include "scv.h"
#endif
#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM 
#include "cve.h"
#endif


class pfm_top_sci : public xsc::utils::xsc_sim_conn_base {

public:
	//Exported sockets declaration
		xtlm::xtlm_aximm_target_socket* C0_DDR4_S_AXI_CTRL_0_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* C0_DDR4_S_AXI_CTRL_0_tlm_aximm_write_socket;;
	
	//Constructor for the module
	pfm_top_sci(const sc_module_name& module_name);
	SC_HAS_PROCESS(pfm_top_sci);
	//Destructor for the module
	~pfm_top_sci();
	
	void initConnModule();

protected:
void before_end_of_elaboration();

private:
	pfm_top_sci(const pfm_top_sci&);
	const pfm_top_sci& operator=(const pfm_top_sci&);
};
#endif
