//File Automatically generated by SystemC Netlister Time
#ifndef PFM_DYNAMIC_SCI_H
#define PFM_DYNAMIC_SCI_H
#include "systemc.h"
#include "xtlm.h"
#include "utils/xtlm_aximm_transview.h"
#include "utils/xtlm_aximm_transaction_logger.h"
#include "utils/xtlm_axis_transaction_logger.h"
#include "pfm_dynamic_xbar_4_sc.h"
#include "pfm_dynamic_m01_regslice_6_sc.h"
#include "pfm_dynamic_auto_cc_0_sc.h"
#include "pfm_dynamic_m01_regslice_7_sc.h"
#include "pfm_dynamic_xbar_5_sc.h"
#include "pfm_dynamic_auto_cc_1_sc.h"
#include "pfm_dynamic_m00_regslice_0_sc.h"
#include "pfm_dynamic_auto_cc_2_sc.h"
#include "pfm_dynamic_m01_regslice_8_sc.h"
#include "pfm_dynamic_auto_cc_3_sc.h"
#include "pfm_dynamic_m02_regslice_0_sc.h"
#include "pfm_dynamic_auto_cc_4_sc.h"
#include "pfm_dynamic_m03_regslice_0_sc.h"
#include "pfm_dynamic_s00_regslice_0_sc.h"
#include "pfm_dynamic_xbar_6_sc.h"
#include "pfm_dynamic_dpa_hub_0_sc.h"
#include "pfm_dynamic_dpa_mon0_0_sc.h"
#include "pfm_dynamic_dpa_mon1_0_sc.h"
#include "pfm_dynamic_profile_vip_0_0_sc.h"
#include "pfm_dynamic_smartconn_data_0_0_sc.h"
#if (defined MTI_SYSTEMC || defined XM_SYSTEMC) && defined XSC_ENABLE_TLM_WAVEFORM 
#include "scv.h"
#endif
#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM 
#include "cve.h"
#endif


class pfm_dynamic_sci : public xsc::utils::xsc_sim_conn_base {

public:
	//Exported sockets declaration
		xtlm::xtlm_aximm_initiator_socket* PLP_M_AXI_DATA_U2S_00_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_initiator_socket* PLP_M_AXI_DATA_U2S_00_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_00_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_00_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_01_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_01_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_02_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_02_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_03_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_DATA_H2C_03_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_CTRL_USER_00_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_CTRL_USER_00_tlm_aximm_write_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_CTRL_USER_01_tlm_aximm_read_socket;;
		xtlm::xtlm_aximm_target_socket* PLP_S_AXI_CTRL_USER_01_tlm_aximm_write_socket;;
	
	//Constructor for the module
	pfm_dynamic_sci(const sc_module_name& module_name);
	SC_HAS_PROCESS(pfm_dynamic_sci);
	//Destructor for the module
	~pfm_dynamic_sci();
	
	void initConnModule();

protected:
void before_end_of_elaboration();

private:
	pfm_dynamic_sci(const pfm_dynamic_sci&);
	const pfm_dynamic_sci& operator=(const pfm_dynamic_sci&);
};
#endif
